- name: Install Redis
  apt:
    name: redis-server
    state: present
    update_cache: yes

- name: Start Redis
  service:
    name: redis-server
    state: started
    enabled: yes

- name: Make backup of Redis configuration
  command: cp /etc/redis/redis.conf /etc/redis/redis.conf.bak
  args:
    creates: /etc/redis/redis.conf.bak

- name: Copy Redis configuration
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
  notify: Restart Redis

- name: Ensure Redis is running
  wait_for:
    port: "{{ redis_port }}"
    delay: 5
    timeout: 300
