- name: Check if Composer is installed
  command: composer --version
  environment:
    COMPOSER_ALLOW_SUPERUSER: "1"
  register: composer_version
  ignore_errors: true

- name: Download Composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
  register: composer_download
  when: composer_version is failed

- name: Install Composer
  command: php /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer
  register: composer_install
  when: composer_version is failed and composer_download is success

- name: Remove Composer installer
  file:
    path: /tmp/composer-installer.php
    state: absent
  when: composer_install is changed
