- name: Add PHP community repository
  apt_repository:
    repo: "ppa:ondrej/php"
    state: present
  when: ansible_os_family == 'Debian' and php_version == '8.3'

- name: Install PHP
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  loop: "{{ packages }}"
  when: ansible_os_family == 'Debian'

- name: Add www.conf
  template:
    src: www.conf.j2
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
  notify: restart php-fpm

- name: Add php.ini
  template:
    src: php.ini.j2
    dest: "/etc/php/{{ php_version }}/fpm/php.ini"
  notify: restart php-fpm
