---

- name: Install pve_exporter
  unarchive:
    src: https://github.com/prometheus-pve/prometheus-pve-exporter/archive/v{{ pve_exporter_version }}.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    extra_opts: ['--strip-components=1']
    exclude: ['LICENSE', 'NOTICE']
  notify: Restart pve_exporter

- name: Configure pve_exporter.service
  template:
    src: pve_exporter.service.j2
    dest: /etc/systemd/system/pve_exporter.service
  notify: Restart pve_exporter

- name: Start pve_exporter
  systemd:
    name: pve_exporter
    state: started
    enabled: true
    daemon_reload: yes
    